import { notFound } from "next/navigation";
import { Download, ExternalLink } from "lucide-react";
import { findProductById, findWinnerByDate } from "@/lib/repositories/catalog";
import { formatMoney } from "@/lib/utils";
import { PageContainer } from "@/components/layout/PageContainer";
import { WinnerBadge } from "@/components/winners/WinnerBadge";
import { ButtonLink } from "@/components/ui/Button";

export async function generateMetadata({ params }: { params: Promise<{ date: string }> }) { const { date } = await params; const winner = await findWinnerByDate(date); return { title: winner ? `${winner.productName} won the brawl` : "Winner" }; }

export default async function WinnerPage({ params }: { params: Promise<{ date: string }> }) { const { date } = await params; const winner = await findWinnerByDate(date); if (!winner) notFound(); const product = await findProductById(winner.productId); if (!product) notFound(); return <PageContainer><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><div className="eyebrow text-coral">Verified daily winner</div><h1 className="display mt-4 text-5xl font-black leading-[.95] tracking-tight sm:text-7xl">{product.name}<br /><span className="text-coral">held the line.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-muted">{product.makerName} finished #1 in the Launch Brawl sponsored leaderboard on {new Date(winner.date).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label="Winning bid" value={formatMoney(winner.winningBidCents)} /><Metric label="Views" value={winner.views.toLocaleString()} /><Metric label="Clicks" value={winner.clicks.toLocaleString()} /></div><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href={`/product/${product.slug}`} variant="dark" size="md">Visit product <ExternalLink size={15} /></ButtonLink><a href={`/api/badges/${winner.id}`} download className="inline-flex items-center gap-2 rounded-[16px] rounded-br-[7px] border border-ink bg-paper px-5 py-3 text-sm font-black text-ink"><Download size={15} />Download badge</a></div></div><div><WinnerBadge name={product.name} date={winner.date} bidCents={winner.winningBidCents} winnerId={winner.id} dark /></div></div><div className="mt-16 border-t border-line pt-8"><p className="text-sm text-muted">Want this page for your launch?</p><ButtonLink href="/submit" variant="ghost" size="sm" arrow className="mt-2 px-0">Submit a product</ButtonLink></div></PageContainer>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-line bg-paper p-4"><p className="eyebrow text-muted">{label}</p><p className="display mt-3 text-xl font-black">{value}</p></div>; }
