import { Eye, HeartHandshake, Scale, Sparkles } from "lucide-react";
import { PageContainer } from "@/components/layout/PageContainer";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { TrustNote } from "@/components/marketing/TrustNote";
import { ButtonLink } from "@/components/ui/Button";

export const metadata = { title: "About" };

export default function AboutPage() { return <PageContainer><SectionHeading eyebrow="Why this exists" title="The internet has plenty of products. It needs better ways to find them." description="Launch Brawl is built around a simple idea: discovery should reward usefulness, momentum, and good stories—not just whoever shouts the loudest." /><div className="mt-12 grid gap-12 lg:grid-cols-[1fr_.8fr]"><div className="space-y-8 text-[15px] leading-8 text-ink/80"><p>Small teams make some of the most thoughtful software on the internet. They also compete with a feed designed to forget everything in a few seconds. Launch Brawl gives those projects a focused place to be seen, understood, and chosen.</p><p>The platform has two lanes: organic discovery and sponsored reach. Votes, clicks, favorites, recency, and category engagement shape what is trending. Paid bids can buy a labeled sponsored position and measurable promotional exposure. The lanes do not pretend to be the same thing.</p><p>That separation matters. It lets people browse without feeling like every recommendation is an ad, and it lets advertisers understand exactly what they purchased.</p><div className="border-l-4 border-coral pl-5 text-xl font-bold leading-8 text-ink">“A launch should be able to earn attention, not rent credibility.”</div></div><div className="grid gap-4">{[{ icon: Scale, title: "Transparent by default", text: "Sponsored means sponsored. The ranking logic is visible in the UI." }, { icon: Eye, title: "Useful measurement", text: "Qualified events, not inflated vanity numbers, power campaigns." }, { icon: HeartHandshake, title: "An open directory", text: "Free listings and organic discovery keep the ecosystem accessible." }, { icon: Sparkles, title: "A little more delight", text: "The web is more fun when curious people can find each other." }].map((item) => <div key={item.title} className="border border-line bg-paper-strong/45 p-5"><item.icon size={19} className="text-coral" /><h2 className="mt-4 text-sm font-bold">{item.title}</h2><p className="mt-1 text-xs leading-5 text-muted">{item.text}</p></div>)}</div></div><div className="mt-14"><TrustNote /></div><div className="mt-10 flex flex-wrap gap-3"><ButtonLink href="/discover" variant="dark" size="md" arrow>Explore the directory</ButtonLink><ButtonLink href="/legal/advertising" variant="secondary" size="md" arrow>Read our ad principles</ButtonLink></div></PageContainer>; }
