import { notFound } from "next/navigation";
import { PageContainer } from "@/components/layout/PageContainer";

const pages: Record<string, { title: string; eyebrow: string; intro: string; sections: Array<{ heading: string; body: string }> }> = {
  terms: { eyebrow: "Legal", title: "Terms of use", intro: "These terms describe the rules for using Launch Brawl as a visitor, maker, advertiser, or administrator.", sections: [{ heading: "Use of the service", body: "You may browse, submit products, vote, and purchase sponsored placement only when you have authority to do so. Do not misrepresent a product, manipulate votes, or use automated traffic to distort discovery or campaign measurement." }, { heading: "Sponsored placement", body: "Sponsored leaderboard positions are paid placements. The highest active bid leads within the configured round, and Launch Brawl labels those placements clearly. Sponsored placement is not an organic endorsement and does not guarantee customers, revenue, or external search rankings." }, { heading: "Payments and refunds", body: "Payments are processed by Freemius, our merchant-of-record checkout provider. A bid becomes active only after server-side webhook or signed redirect verification. Any refund policy that applies to undelivered promotional allocation is governed by the commercial policy configured for the campaign and Freemius." }] },
  privacy: { eyebrow: "Legal", title: "Privacy", intro: "Launch Brawl should collect only what is needed to operate discovery, attribution, payments, and account features.", sections: [{ heading: "Information we use", body: "Account details come from authentication. Product owners provide listing content. Campaign events may include a product, campaign, placement, page, timestamp, referrer, device classification, viewport, and an anonymized session or network fingerprint where appropriate." }, { heading: "Event qualification", body: "We filter obvious crawlers, rapid repeats, and suspicious request bursts. Raw events should be retained according to a documented policy and summarized into daily aggregate documents for cost and privacy control." }, { heading: "Your choices", body: "You can request account or product changes through the configured support channel. Integrations such as Clerk, Freemius, Resend, Redis, and storage providers process data only when enabled in the deployment." }] },
  advertising: { eyebrow: "Ad principles", title: "Advertising that says what it is", intro: "Launch Brawl exists to make paid reach useful without making it look like organic consensus.", sections: [{ heading: "Sponsored is always visible", body: "Paid placements are labeled Sponsored Leaderboard or Sponsored. We do not merge bid amount into trending, most-loved, new, or category organic rankings." }, { heading: "Every successful bid creates a campaign", body: "The commercial formula is configured in admin settings. A successful bid creates promotional impression credits, which are delivered through available inventory and measured with qualified events." }, { heading: "No guarantees we cannot prove", body: "We do not promise customers, sales, profit, backlinks, Google rankings, ChatGPT rankings, or any outcome outside the measurable Launch Brawl inventory and tracked interactions." }] },
  refunds: { eyebrow: "Legal", title: "Refund policy", intro: "Payments and campaign allocation should be handled with clear records and no invented guarantees.", sections: [{ heading: "Payment verification", body: "Freemius is authoritative for payment success, license status, and merchant-of-record receipts. Local records are synchronized by verified webhooks and signed redirects and are designed to be idempotent if an event is replayed." }, { heading: "Campaign allocation", body: "Being outbid changes a product’s leaderboard position, not the promotional allocation already purchased. Campaigns remain active until their qualified impression allocation is fulfilled unless an administrator pauses or refunds them under the configured commercial policy." }, { heading: "Contact", body: "For a production deployment, publish a monitored support address and the jurisdiction-specific terms required for your business before accepting live payments." }] },
  cookies: { eyebrow: "Legal", title: "Cookies & sessions", intro: "Launch Brawl uses small pieces of storage to keep the product useful, secure, and attributable.", sections: [{ heading: "Essential storage", body: "Authentication, theme preference, and security controls may use cookies or local storage. These are required for the corresponding experience to work." }, { heading: "Campaign measurement", body: "A campaign impression or click may use an anonymous session identifier and cooldown window to reduce duplicate counting. This is not a promise that every browser or privacy setting can be measured." }, { heading: "Your controls", body: "You can control cookies through your browser. Production deployments should add a consent experience appropriate to their jurisdictions and analytics choices." }] },
};

export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; return { title: page?.title ?? "Legal" }; }
export default async function LegalPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; if (!page) notFound(); return <PageContainer className="max-w-[940px]"><div className="border-b border-line pb-10"><div className="eyebrow text-coral">{page.eyebrow}</div><h1 className="display mt-4 text-5xl font-black tracking-tight sm:text-7xl">{page.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted">{page.intro}</p></div><div className="mt-10 grid gap-8 sm:grid-cols-[180px_1fr]"><div className="eyebrow text-muted">Last updated<br />August 2026</div><div className="grid gap-8">{page.sections.map((section) => <section key={section.heading} className="border-b border-line pb-8 last:border-0"><h2 className="display text-2xl font-black">{section.heading}</h2><p className="mt-3 text-[15px] leading-8 text-ink/75">{section.body}</p></section>)}</div></div></PageContainer>; }
