import { ArrowUpRight, BadgePercent, Gift, Timer } from "lucide-react";
import { getProductsByIds, listActiveDeals } from "@/lib/repositories/catalog";
import { PageContainer } from "@/components/layout/PageContainer";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { ProductLogo } from "@/components/products/ProductLogo";

export const metadata = { title: "Deals" };
export const dynamic = "force-dynamic";

export default async function DealsPage() { const deals = await listActiveDeals(); const products = await getProductsByIds(deals.map((deal) => deal.productId)); const byId = new Map(products.map((product) => [product.id, product])); return <PageContainer><SectionHeading eyebrow="Maker offers" title="Good things, for less" description="Limited offers from products on the board. No fake urgency—just transparent terms from the makers themselves." /><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{deals.map((deal) => { const product = byId.get(deal.productId); return product ? <article key={deal.id} className="border border-line bg-paper p-5"><div className="flex items-start justify-between"><ProductLogo product={product} size="md" /><span className="flex h-8 w-8 items-center justify-center rounded-full bg-coral/10 text-coral"><BadgePercent size={16} /></span></div><h2 className="display mt-6 text-2xl font-black">{product.name}</h2><p className="mt-2 text-sm font-bold text-ink">{deal.title}</p>{deal.description && <p className="mt-2 text-sm leading-6 text-muted">{deal.description}</p>}{deal.couponCode && <p className="mt-4 inline-flex rounded-full border border-coral/30 bg-coral/5 px-3 py-1.5 text-xs font-black text-coral">Code: {deal.couponCode}</p>}<div className="mt-6 flex items-center justify-between border-t border-line pt-4"><span className="inline-flex items-center gap-1.5 text-xs font-bold text-muted"><Timer size={13} />{deal.expiresAt ? `Until ${new Date(deal.expiresAt).toLocaleDateString()}` : "Offer terms on maker site"}</span><a href={deal.destinationUrl || `/go/${product.id}?placement=deals`} target={deal.destinationUrl ? "_blank" : undefined} rel={deal.destinationUrl ? "noreferrer" : undefined} className="inline-flex items-center gap-1 text-xs font-bold text-ink underline decoration-coral decoration-2 underline-offset-4">View offer <ArrowUpRight size={14} /></a></div></article> : null; })}</div>{!deals.length && <div className="mt-10"><p className="border border-dashed border-line p-10 text-center text-sm text-muted">No active maker offers right now.</p></div>}<div className="mt-10 flex items-start gap-3 border border-line bg-paper-strong/55 p-5 text-sm leading-6 text-muted"><Gift size={18} className="mt-0.5 shrink-0 text-coral" />Deals are supplied by makers and are not a paid ranking. Launch Brawl links out through tracked redirects so makers can learn where interest came from.</div></PageContainer>; }
