import { BarChart3, Check, Flag, Gift, ShieldCheck } from "lucide-react";
import { PageContainer } from "@/components/layout/PageContainer";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { ButtonLink } from "@/components/ui/Button";

export const metadata = { title: "Pricing" };

export default function PricingPage() { return <PageContainer><SectionHeading eyebrow="The transparent model" title="Pay for reach. Keep the signal." description="Launch Brawl is free to list. Sponsored placement is an optional campaign layer for makers who want more measurable exposure." /><div className="mt-10 grid gap-4 lg:grid-cols-2"><Plan title="Free listing" price="$0" eyebrow="Start here" tone="paper" description="A real home for your product, whether or not you ever bid." features={["Product profile", "Organic discovery", "Community votes & favorites", "Category listings", "Shareable product URL"]} cta="Submit a product" href="/submit" /><Plan title="The Brawl" price="Pay as you bid" eyebrow="Optional sponsored reach" tone="coral" description="A 24-hour sponsored leaderboard position plus a campaign allocation that keeps delivering if you are outbid." features={["Sponsored leaderboard position", "Promotional impression credits", "Qualified click tracking", "Campaign analytics dashboard", "Winner eligibility & badge", "Permanent bid history"]} cta="See today’s brawl" href="/#daily-brawl" /></div><div className="mt-12"><div className="border border-line bg-paper-strong/55 p-6 sm:p-8"><div className="eyebrow text-coral">What your bid buys</div><h2 className="display mt-3 text-3xl font-black">Money buys exposure, not a promise.</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[{ icon: Flag, title: "Position", text: "Highest active bid leads, clearly marked Sponsored." }, { icon: Gift, title: "Allocation", text: "Configured impression credits attach to every paid bid." }, { icon: BarChart3, title: "Measurement", text: "Qualified impressions, clicks, CTR, CPC, and sources." }, { icon: ShieldCheck, title: "Fairness", text: "No guaranteed customers, sales, or external rankings." }].map((item) => <div key={item.title}><item.icon size={18} className="text-coral" /><p className="mt-4 text-sm font-bold">{item.title}</p><p className="mt-1 text-xs leading-5 text-muted">{item.text}</p></div>)}</div></div></div></PageContainer>; }

function Plan({ title, price, eyebrow, description, features, cta, href, tone }: { title: string; price: string; eyebrow: string; description: string; features: string[]; cta: string; href: string; tone: "paper" | "coral" }) { return <div className={`border p-6 sm:p-8 ${tone === "coral" ? "border-coral bg-coral text-white shadow-[7px_7px_0_#14212b]" : "border-line bg-paper"}`}><div className={`eyebrow ${tone === "coral" ? "text-white/65" : "text-coral"}`}>{eyebrow}</div><h2 className="display mt-4 text-3xl font-black">{title}</h2><p className={`mt-3 text-sm leading-6 ${tone === "coral" ? "text-white/75" : "text-muted"}`}>{description}</p><p className="display mt-8 text-4xl font-black">{price}</p><div className={`mt-7 grid gap-3 border-t pt-6 ${tone === "coral" ? "border-white/20" : "border-line"}`}>{features.map((feature) => <div key={feature} className="flex items-center gap-2 text-sm"><Check size={15} className={tone === "coral" ? "text-white" : "text-coral"} />{feature}</div>)}</div><ButtonLink href={href} variant={tone === "coral" ? "secondary" : "dark"} size="md" arrow className="mt-8">{cta}</ButtonLink></div>; }
