import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Compass, Sparkles, TrendingUp } from "lucide-react";
import { listTastemakers } from "@/lib/repositories/competitive";
import { PageContainer } from "@/components/layout/PageContainer";
import { SectionHeading } from "@/components/ui/SectionHeading";

export const metadata: Metadata = { title: "Tastemakers", description: "People who discover promising products before they become popular." };
export const dynamic = "force-dynamic";

export default async function TastemakersPage() {
  const tastemakers = (await listTastemakers()).filter((entry): entry is typeof entry & { user: NonNullable<typeof entry.user> } => Boolean(entry.user));
  return <PageContainer><SectionHeading eyebrow="Find signal early" title="Tastemakers" description="A transparent leaderboard for people who support promising products before the crowd catches up." /><section className="mt-10 border-2 border-ink bg-ink p-6 text-white sm:p-8"><div className="flex items-start gap-4"><Compass className="shrink-0 text-coral" size={25} /><div><div className="eyebrow text-white/50">How the score works</div><h2 className="display mt-2 text-3xl font-black">Early support, measured honestly.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Tastemaker Score considers organic growth after your support, trending movement, and later Brawl performance. Paid sponsored position is excluded, and repeated early votes have diminishing returns.</p></div></div></section><div className="mt-8 overflow-hidden border-y border-line"><div className="hidden grid-cols-[58px_1fr_130px_110px_110px_85px] gap-3 bg-paper-strong/55 px-4 py-3 text-[10px] font-black uppercase tracking-[0.1em] text-muted md:grid"><span>#</span><span>Person</span><span>Level</span><span>Score</span><span>Early finds</span><span>Accuracy</span></div>{tastemakers.map(({ stats, user }, index) => <Link key={user.username} href={`/profile/${user.username}`} className="grid gap-3 border-b border-line px-4 py-5 last:border-0 hover:bg-paper-strong/35 md:grid-cols-[58px_1fr_130px_110px_110px_85px] md:items-center"><span className="display text-2xl font-black">#{index + 1}</span><span><span className="block text-sm font-black">{user.displayName}</span><span className="mt-1 block text-xs text-muted">@{user.username}</span></span><span className="text-xs font-bold">Level {stats.level}</span><span className="text-sm font-black text-coral">{stats.tastemakerScore.toLocaleString()}</span><span className="text-xs font-bold">{stats.earlyFinds}</span><span className="text-xs font-bold">{stats.predictionAccuracy}%</span></Link>)}</div>{!tastemakers.length && <p className="mt-8 border border-dashed border-line p-10 text-center text-sm text-muted">Tastemaker rankings appear after real community predictions and product engagement accumulate.</p>}<div className="mt-8 grid gap-3 sm:grid-cols-3"><Info icon={<Sparkles size={17} />} title="Early Finds" body="Support before organic momentum is obvious." /><Info icon={<TrendingUp size={17} />} title="Organic only" body="Sponsored impressions never award score directly." /><Info icon={<ArrowUpRight size={17} />} title="Share discoveries" body="Give your profile a public record of good calls." /></div></PageContainer>;
}

function Info({ icon, title, body }: { icon: React.ReactNode; title: string; body: string }) { return <div className="border border-line bg-paper p-5"><span className="text-coral">{icon}</span><p className="mt-4 text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 text-muted">{body}</p></div>; }
