import Link from "next/link";
import { ArrowUpRight, Flame, Sparkles, Trophy } from "lucide-react";
import { getUserGamification, listUserAchievements } from "@/lib/repositories/competitive";

export async function UserGamificationPanel({ userId, compact = false }: { userId: string; compact?: boolean }) {
  const [stats, achievements] = await Promise.all([getUserGamification(userId), listUserAchievements(userId)]);
  return <section className={`border border-ink bg-ink p-5 text-white ${compact ? "mt-6" : "mt-10"}`}><div className="flex items-start justify-between gap-3"><div><div className="eyebrow text-white/50">Community identity</div><h2 className="display mt-2 text-2xl font-black">Level {stats.level} — {stats.levelTitle}</h2></div><Sparkles size={19} className="text-coral" /></div><div className="mt-5 grid grid-cols-2 gap-2"><Metric label="XP" value={stats.xp.toLocaleString()} /><Metric label="Tastemaker" value={stats.tastemakerScore.toLocaleString()} /><Metric label="Accuracy" value={`${stats.predictionAccuracy}%`} /><Metric label="Streak" value={`🔥 ${stats.currentPredictionStreak}`} /></div><div className="mt-5 grid gap-2 text-xs text-white/65"><span className="inline-flex items-center gap-2"><Trophy size={14} className="text-coral" />{stats.earlyFinds} early finds</span><span className="inline-flex items-center gap-2"><Flame size={14} className="text-coral" />Best prediction streak {stats.bestPredictionStreak}</span></div>{achievements.length ? <div className="mt-5 border-t border-white/10 pt-4"><p className="eyebrow text-white/45">Trophy Cabinet</p><div className="mt-3 flex flex-wrap gap-2">{achievements.slice(0, 6).map((achievement) => <span key={achievement.id} title={achievement.description} className="rounded-full border border-coral/50 px-2.5 py-1 text-[10px] font-black text-coral">{achievement.name}</span>)}</div></div> : null}<Link href="/quests" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-white underline decoration-coral decoration-2 underline-offset-4">See today&apos;s progression <ArrowUpRight size={14} /></Link></section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-white/10 bg-white/5 p-3"><span className="block text-[10px] font-black uppercase tracking-[0.1em] text-white/45">{label}</span><span className="mt-1 block text-sm font-black">{value}</span></div>; }
